# Generated by Django 3.2.8 on 2023-11-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='licenseInfo',
            new_name='license_info',
        ),
        migrations.AddField(
            model_name='doctor',
            name='timings',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctors.AvailabilityTimeTable'),
        ),
        migrations.AlterField(
            model_name='availabilitytimetable',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_timetables', to='doctors.doctor'),
        ),
    ]
