# Generated by Django 3.2.8 on 2023-11-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20231127_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilitytimetable',
            options={'permissions': [('can_add_time_slots', 'Can add time slots')]},
        ),
    ]
