# Generated by Django 3.2.8 on 2023-11-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20231122_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
