# Generated by Django 3.2.8 on 2023-11-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_availabilitytimetable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitytimetable',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availabilitytimetable',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
