# Generated by Django 3.2.8 on 2023-11-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_emergencycontacts'),
        ('doctors', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(blank=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='doctors.availabilitytimetable')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='user_profile.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
