# Generated by Django 3.2.8 on 2023-11-22 11:56

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_emergencycontacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0005_auto_20231122_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=255)),
                ('diagnosis', models.CharField(max_length=255)),
                ('prescription', models.CharField(max_length=255)),
                ('prescription_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('diagnosis_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('remarks', models.CharField(max_length=255)),
                ('remarks_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('approved_remarks', models.TextField(blank=True)),
                ('rejected_remarks', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_approved_by', to=settings.AUTH_USER_MODEL)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='doctors.availabilitytimetable')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='user_profile.profile')),
                ('rejected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_rejected_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
