# Generated by Django 3.2.8 on 2023-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_auto_20231127_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilitytimetable',
            options={},
        ),
        migrations.AddField(
            model_name='availabilitytimetable',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
