# Generated by Django 3.2.8 on 2023-11-22 12:18

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_emergencycontacts'),
        ('doctors', '0006_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='approved_remarks',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='prescription_image',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='rejected_remarks',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='remarks_image',
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=255)),
                ('prescription_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('remarks', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.availabilitytimetable')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='user_profile.profile')),
            ],
        ),
    ]
