# Generated by Django 3.2.8 on 2023-11-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_auto_20231127_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitytimetable',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
