# Generated by Django 3.2.8 on 2023-12-09 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_auto_20231127_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitytimetable',
            name='selected_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SelectedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_time', models.TimeField()),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_times', to='doctors.availabilitytimetable')),
            ],
        ),
    ]
